apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  namespace: default
spec:
  selector:
    matchLabels:
      app: test1
  replicas: 1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
        - name: test1
          image: nurlan1992/test1:test1-943162e
          ports:
            - containerPort: 5000
